data: # root path of train/validation data (either relative/absoulte path is ok)
  train: '/media/datka/Datasets/Russian/argentinetz/wavs'
  validation: '/media/datka/Datasets/Russian/argentinetz/3samples'
  mel_path: '/media/datka/Datasets/Russian/argentinetz/vec'
  eval_path: ''
---
train:
  rep_discriminator: 1
  discriminator_train_start_steps: 50000
  num_workers: 4
  batch_size: 16
  optimizer: 'adam'
  adam:
    lr: 0.0002
    beta1: 0.8
    beta2: 0.99
    lr_decay: 0.999
---
audio:
  n_mel_channels: 392
  segment_length: 16000
  pad_short: 2000
  filter_length: 1024
  hop_length: 320
  win_length: 320
  sampling_rate: 16000
  mel_fmin: 0.0
  mel_fmax: 8000.0
---
model:
  feat_match: 10.0
  lambda_adv: 1
  lambda_mel: 45
  use_subband_stft_loss: False
  feat_loss: True
  out_channels: 1
  generator_ratio: [ 5, 4, 4, 2, 2] # product should be equal to hop length
  generator_kernel_sizes: [ 11, 8, 8, 4, 4]
  discriminator_periods: [ 2, 3, 5, 7, 9, 11 ]
  mult: 512
  n_residual_layers: 4
  num_D : 3
  ndf : 16
  n_layers: 3
  downsampling_factor: 4
  disc_out: 512
  
stft_loss_params:
    fft_sizes: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
    hop_sizes: [120, 240, 50]     # List of hop size for STFT-based loss
    win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
    window: "hann_window"         # Window function for STFT-based loss
subband_stft_loss_params:
  fft_sizes: [384, 683, 171]  # List of FFT size for STFT-based loss.
  hop_sizes: [30, 60, 10]     # List of hop size for STFT-based loss
  win_lengths: [150, 300, 60] # List of window length for STFT-based loss.
  window: "hann_window"       # Window function for STFT-based loss
---
log:
  summary_interval: 10
  validation_interval: 5
  save_interval: 20
  chkpt_dir: '/media/datka/checkpoints/hifigan'
  log_dir: 'logs'
